### ISSUE TITLE
Please rename the project

### ISSUE THREAD

**Issue by snicoll** [jmnarloch/modelmapper-spring-boot-starter#1]
Hey,

We're asking 3rd party code not [to use the `spring-boot` prefix](http://docs.spring.io/spring-boot/docs/1.3.0.M3/reference/htmlsingle/#using-boot-starter-poms). Could you please rename it?

Let me know when you're done so that I can add it to the list of 3rd party starters.

**Comment by jmnarloch** [comment]
Done.
