### ISSUE TITLE
Configuration issue

### ISSUE THREAD

**Issue by jmiazga** [jmnarloch/modelmapper-spring-boot-starter#2]
I have an issue where I define multiple mappings by extending PropertyMapConfigurerSupport, and also a configuration by implementing ModelMapperConfigurer. In my configuration I set the matching strategy to STRICT. 

The issue I am having is that the configuration is not set before the mappings are.

In ModelMapperFactoryBean.java, in the configure method, the list of configurers is in alphabetical order. If my configuration class starts with a letter before any of my mapping classes, I dont have an issue. But if it is somewhere else in the list, ModelMapper throws an error, which would be avoided if my matching strategy was set to STRICT.

Is there a way I can force the configuration to run before the mappings? Can you update your code to have this happen?

Thanks,
Jason

**Comment by jmnarloch** [comment]
Hey Jason,

I think that there is no need to make changes in this module at all. What you should be able to do is leverage the Spring's ordering functionality by using @Order annotation, you can place that on your bean class declaration or on the @Configuration methods. I have prepared a test that illustrates your use case: https://github.com/jmnarloch/modelmapper-spring-boot-starter/blob/master/src/test/java/com/github/jmnarloch/spring/boot/modelmapper/ModelMapperOrdererConfigurerTest.java#L120

Hope that this helps.

**Comment by jmiazga** [comment]
Thanks for the quick response. Using the @Order annotation solved my issue. Thanks again!
