### ISSUE TITLE
Support for converter

### ISSUE THREAD

**Issue by jmiazga** [jmnarloch/modelmapper-spring-boot-starter#3]
Are there any plans to add support for a converter. I can accomplish this by implementing ModelMapperConfigurer, but it would be cleaner if we could handle it in a similar fashion to a PropertyMap.

**Comment by jmnarloch** [comment]
I've added relevant class: https://github.com/jmnarloch/modelmapper-spring-boot-starter/commit/6f139a0585d8f126af09dab8bccf62e76a739d3f

The release 1.1.0 including this change, should be available from maven central within an hour.

**Comment by jmiazga** [comment]
Thanks again!
